public enum VoiceOptionsMonoAndMultiModel
{
    Jessie = 0,
    Harry = 1,
    Glinda = 2,
    Clyde = 3,
    Freya = 4,
    Fin = 5,
    Dave = 6,
    Charlotte = 7, 
    Callum = 8,
    Arthur = 9,
    Hailey = 10,
    Batman = 11,
    Andrew = 12,
    Anime_Girl = 13,
    Valentina = 14,
    Wayne = 15,
    Jan = 16,
    Noah = 17,
    Lily = 18,
    Ethan = 19,
    Sophia = 20,
    Olivia = 21,
    Ruby = 22,
    Lucas = 23,
    John = 24,
}